# Generated by Django 3.0.5 on 2020-07-25 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
